import hashlib
import json
import plistlib
from pathlib import Path
import shutil
import subprocess
import tempfile
import unittest

import release_tools as tools


class ReleaseToolsTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        for name in ["docs/changes", "docs/releases", "Config"]:
            (self.root / name).mkdir(parents=True)
        info = plistlib.loads((tools.ROOT / "Config/Info.plist").read_bytes())
        info["CFBundleShortVersionString"] = "1.0.0"
        (self.root / "Config/Info.plist").write_bytes(plistlib.dumps(info))
        self.record = dict(version="1.0.0", date="2026-09-30", firstPublicRelease=True, previousPublicTag=None)
        tools.write_json(self.root / "docs/releases/1.0.0.json", self.record)
        self.fragment = dict(id="test-change", version="1.0.0", category="fixed", technical="A < B & C [link](https://example.org)", user="Safe text", commits=[])
        self.fragment_path = self.root / "docs/changes/test-change.json"
        tools.write_json(self.fragment_path, self.fragment)

    def render(self):
        for name, content in tools.render_documents(self.root).items():
            (self.root / name).write_text(content)

    def test_deterministic_generation_and_escaping(self):
        before = tools.render_documents(self.root)
        self.assertEqual(before, tools.render_documents(self.root))
        self.assertIn(r"A \< B & C \[link\]", before["CHANGELOG.md"])
        self.assertNotIn("### Engineering", before["docs/RELEASE_NOTES.md"])
        self.render()
        tools.validate_documents(self.root)
        notes = tools.version_notes("1.0.0", self.root)
        self.assertTrue(notes.startswith("## 1.0.0"))
        self.assertNotIn("Generated by", notes)

    def test_stale_output_and_version_mismatch_fail(self):
        self.render()
        (self.root / "CHANGELOG.md").write_text("stale")
        with self.assertRaisesRegex(ValueError, "Stale"):
            tools.validate_documents(self.root)
        self.render()
        text = (self.root / "Config/Info.plist").read_text().replace("1.0.0", "1.0.1")
        (self.root / "Config/Info.plist").write_text(text)
        with self.assertRaisesRegex(ValueError, "disagree"):
            tools.validate_documents(self.root)

    def test_malformed_or_unverified_fragment_is_rejected(self):
        for change in [dict(category="unknown"), dict(technical="line\ninjection"), dict(commits=["#42"]), dict(extra=True), dict(user="", skipReason="internal")]:
            tools.write_json(self.fragment_path, {**self.fragment, **change})
            with self.assertRaises(ValueError):
                tools.fragments(self.root)

    def test_internal_entries_and_related_summaries_deduplicate(self):
        tools.write_json(self.root / "docs/changes/other-change.json", {**self.fragment, "id": "other-change"})
        result = tools.render_documents(self.root)
        self.assertEqual(result["docs/RELEASE_NOTES.md"].count("- Safe text"), 1)
        tools.write_json(self.fragment_path, {**self.fragment, "user": None, "skipReason": "Internal instrumentation only"})
        tools.write_json(self.root / "docs/changes/other-change.json", {**self.fragment, "id": "other-change", "user": None})
        self.assertNotIn("### Fixed", tools.render_documents(self.root)["docs/RELEASE_NOTES.md"])

    def test_previous_releases_are_preserved(self):
        self.render()
        previous = tools.version_notes("1.0.0", self.root)
        subprocess.run(["git", "init", "-q", str(self.root)], check=True)
        for key, value in [("user.name", "Fixture"), ("user.email", "fixture@example.org")]:
            subprocess.run(["git", "-C", str(self.root), "config", key, value], check=True)
        subprocess.run(["git", "-C", str(self.root), "add", "."], check=True)
        subprocess.run(["git", "-C", str(self.root), "commit", "-qm", "feat: initial fixture"], check=True)
        subprocess.run(["git", "-C", str(self.root), "tag", "v1.0.0"], check=True)
        tools.write_json(self.root / "docs/releases/1.0.1.json", dict(version="1.0.1", date="2026-10-01", firstPublicRelease=False, previousPublicTag="v1.0.0"))
        tools.write_json(self.root / "docs/changes/new-change.json", {**self.fragment, "id": "new-change", "version": "unreleased"})
        subprocess.run(["git", "-C", str(self.root), "add", "docs/changes/new-change.json"], check=True)
        subprocess.run(["git", "-C", str(self.root), "commit", "-qm", "fix: documented follow-up"], check=True)
        contribution = tools.git("rev-parse", "HEAD", root=self.root)
        tools.prepare("1.0.1", "2026-10-01", "v1.0.0", self.root)
        self.assertEqual(previous, tools.version_notes("1.0.0", self.root))
        self.assertEqual(tools.marketing_version(self.root), "1.0.1")
        self.assertEqual(tools.read_json(self.root / "docs/changes/new-change.json")["version"], "1.0.1")
        self.assertIn(contribution, tools.read_json(self.root / "docs/changes/new-change.json")["commits"])

    def test_ci_sequence_handles_predecessors_and_attempts(self):
        self.assertGreater(tools.ci_build_number(1, 1), 108)
        self.assertGreater(tools.ci_build_number(1, 2), tools.ci_build_number(1, 1))
        self.assertGreater(tools.ci_build_number(2, 1), tools.ci_build_number(1, 99))
        for arguments in [(0, 1), (1, 0), (1, 100), (1, 1, [2000])]:
            with self.assertRaises(ValueError):
                tools.ci_build_number(*arguments)

    def test_pending_or_stale_acceptance_fails_closed(self):
        with unittest.mock.patch.object(tools, "product_digest", return_value="digest"):
            record = dict(version="1.0.0", productDigest="digest", reviewedReleaseNotesSHA256="pending", checks={})
            tools.write_json(self.root / "docs/release-acceptance.json", record)
            with self.assertRaisesRegex(ValueError, "pending"):
                tools.validate_acceptance(self.root)
            self.render()
            record["checks"] = {name: dict(status="passed", evidence="Owner observed in a development package") for name in ["realMenuBar", "freshInstallAndPermissions", "firstApplyUndoRelaunch", "loginLifecycle", "uninstallAndRestoration", "sleep", "display"]}
            record["reviewedReleaseNotesSHA256"] = hashlib.sha256(tools.version_notes("1.0.0", self.root).encode()).hexdigest()
            record["checks"]["display"] = dict(status="limited", evidence="Only the guest display was exercised")
            tools.write_json(self.root / "docs/release-acceptance.json", record)
            tools.validate_acceptance(self.root)
            record["productDigest"] = "stale"
            tools.write_json(self.root / "docs/release-acceptance.json", record)
            with self.assertRaisesRegex(ValueError, "current"):
                tools.validate_acceptance(self.root)

    def test_direct_and_merged_commits_need_reconciliation(self):
        subprocess.run(["git", "init", "-q", str(self.root)], check=True)
        for key, value in [("user.name", "Fixture"), ("user.email", "fixture@example.org")]:
            subprocess.run(["git", "-C", str(self.root), "config", key, value], check=True)
        subprocess.run(["git", "-C", str(self.root), "add", "."], check=True)
        subprocess.run(["git", "-C", str(self.root), "commit", "-qm", "feat: initial fixture"], check=True)
        subprocess.run(["git", "-C", str(self.root), "tag", "v1.0.0"], check=True)
        subprocess.run(["git", "-C", str(self.root), "commit", "--allow-empty", "-qm", "fix: direct change"], check=True)
        commit = tools.git("rev-parse", "HEAD", root=self.root)
        self.record.update(firstPublicRelease=False, previousPublicTag="v1.0.0")
        tools.write_json(self.root / "docs/releases/1.0.0.json", self.record)
        with self.assertRaisesRegex(ValueError, "Unreconciled"):
            tools.validate_coverage(self.root)
        tools.write_json(self.fragment_path, {**self.fragment, "commits": [commit]})
        tools.validate_coverage(self.root)
        subprocess.run(["git", "-C", str(self.root), "commit", "--allow-empty", "-qm", "docs: preparation\n\nRelease-Note: none (generated release metadata)"], check=True)
        tools.validate_coverage(self.root)


if __name__ == "__main__":
    import unittest.mock
    unittest.main()
